from typing import Protocol, List, Dict, Any

class LLMTools(Protocol):

    def create_model(self, base_model: str, model_name: str, system_role: str) -> bool: ...
    
    def list_models(self) -> List[Dict[str, Any]]: ...
    
    def chat(self, model_name: str, message: str) -> str: ...
